class ControllerHorarios {
  final List<String> listHours = [
    '6:00 - 7:15',
    '7:15 - 7:30',
    '7:30 - 8:00',
    '8:00 - 8:10',
    '8:10 - 8:30',
    '8:30 - 9:00',
    '9:00 - 9:30',
    '9:30 - 10:00',
    '10:00 - 10:30',
    '10:30 - 11:00',
    '11:00 - 12:00',
    '12:00 - 12:30',
    '12:30 - 1:00',
    '1:00 - 1:30',
    '1:30 - 2:00',
    '2:00 - 3:00',
    '3:00 - 4:30',
    '4:30 - 5:00',
    '5:00 - 5:00',
  ];

  final List<String> listScheduleMondayToSaturday = [
    'Introducción PSAM',
    'Himnos y cánticos',
    'Estudio Vida',
    'Lectura PSAM',
    'Himnos y cánticos',
    'Estudio Vida',
    'Mensajes creyentes nuevos',
    'Himnos y cánticos',
    'Estudio Vida',
    'Himnos y cánticos',
    'Mensaje Buen Depósito',
    'Himnos y cánticos',
    'Lectura Biblia',
    'Himnos y cánticos',
    'Estudio Vida',
    'Niños',
    'Jóvenes',
    'Estudio Vida',
    'Himnos y cánticos',
  ];

  final List<String> listShceduleSunday = [
    'Introducción PSAM',
    'Himnos y cánticos',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'Niños',
    '',
    '',
    'Jóvenes',
    '',
    'Himnos y cánticos',
    '',
  ];
}
